export const IconCategory = {
  Ai: 'ai',
  Alerts: 'alerts',
  Animals: 'animals',
  Arrows: 'arrows',
  AudioAndVideo: 'audioAndVideo',
  Banking: 'banking',
  Bathroom: 'bathroom',
  Bookmarks: 'bookmarks',
  Brands: 'brands',
  Calls: 'calls',
  Charts: 'charts',
  City: 'city',
  Chats: 'chats',
  Cloud: 'cloud',
  Coding: 'coding',
  Computer: 'computer',
  CreativeDesign: 'creativeDesign',
  DatabaseAndServers: 'dbAndServers',
  DateAndTime: 'dateAndTime',
  Delivery: 'delivery',
  Devices: 'devices',
  DocumentsAndFolders: 'docsAndFolders',
  Electricity: 'electricity',
  Emojis: 'emojis',
  Festive: 'festive',
  FiltersAndSettings: 'filtersAndSettings',
  Financial: 'financial',
  Food: 'food',
  Games: 'games',
  Gestures: 'gestures',
  Health: 'health',
  Hearts: 'hearts',
  Home: 'home',
  Interface: 'interface',
  Kitchen: 'kitchen',
  Mail: 'mail',
  Maps: 'maps',
  Nature: 'nature',
  Network: 'network',
  Photos: 'photos',
  School: 'school',
  SearchAndScan: 'searchAndScan',
  Security: 'security',
  Shapes: 'shapes',
  Shopping: 'shopping',
  SpaceAndStars: 'spaceAndStars',
  Sports: 'sports',
  Symbols: 'symbols',
  Tags: 'tags',
  TextAndNumbers: 'textAndNumbers',
  Tickets: 'tickets',
  Travel: 'travel',
  User: 'user',
  Vehicles: 'vehicles',
  Weather: 'weather',
  Other: 'other',
} as const;
export type IconCategory = typeof IconCategory[keyof typeof IconCategory];

export const CATEGORY_LABELS: Record<IconCategory, string> = {
  [IconCategory.Ai]: 'AI',
  [IconCategory.Alerts]: 'Alerts',
  [IconCategory.Animals]: 'Animals',
  [IconCategory.Arrows]: 'Arrows',
  [IconCategory.AudioAndVideo]: 'Audio & Video',
  [IconCategory.Banking]: 'Banking',
  [IconCategory.Bathroom]: 'Bathroom',
  [IconCategory.Bookmarks]: 'Bookmarks',
  [IconCategory.Brands]: 'Brands',
  [IconCategory.Calls]: 'Calls',
  [IconCategory.Charts]: 'Charts',
  [IconCategory.City]: 'City',
  [IconCategory.Chats]: 'Chats',
  [IconCategory.Cloud]: 'Cloud',
  [IconCategory.Coding]: 'Coding',
  [IconCategory.Computer]: 'Computer',
  [IconCategory.CreativeDesign]: 'Creative Design',
  [IconCategory.DatabaseAndServers]: 'Database & Servers',
  [IconCategory.DateAndTime]: 'Date & Time',
  [IconCategory.Delivery]: 'Delivery',
  [IconCategory.Devices]: 'Devices',
  [IconCategory.DocumentsAndFolders]: 'Documents & Folders',
  [IconCategory.Electricity]: 'Electricity',
  [IconCategory.Emojis]: 'Emojis',
  [IconCategory.Festive]: 'Festive',
  [IconCategory.FiltersAndSettings]: 'Filters & Settings',
  [IconCategory.Financial]: 'Financial',
  [IconCategory.Food]: 'Food',
  [IconCategory.Games]: 'Games',
  [IconCategory.Gestures]: 'Gestures',
  [IconCategory.Health]: 'Health',
  [IconCategory.Hearts]: 'Hearts',
  [IconCategory.Home]: 'Home',
  [IconCategory.Interface]: 'Interface',
  [IconCategory.Kitchen]: 'Kitchen',
  [IconCategory.Mail]: 'Mail',
  [IconCategory.Maps]: 'Maps',
  [IconCategory.Nature]: 'Nature',
  [IconCategory.Network]: 'Network',
  [IconCategory.Photos]: 'Photos',
  [IconCategory.School]: 'School',
  [IconCategory.SearchAndScan]: 'Search & Scan',
  [IconCategory.Security]: 'Security',
  [IconCategory.Shapes]: 'Shapes',
  [IconCategory.Shopping]: 'Shopping',
  [IconCategory.SpaceAndStars]: 'Space & Stars',
  [IconCategory.Sports]: 'Sports',
  [IconCategory.Symbols]: 'Symbols',
  [IconCategory.Tags]: 'Tags',
  [IconCategory.TextAndNumbers]: 'Text & Numbers',
  [IconCategory.Tickets]: 'Tickets',
  [IconCategory.Travel]: 'Travel',
  [IconCategory.User]: 'User',
  [IconCategory.Vehicles]: 'Vehicles',
  [IconCategory.Weather]: 'Weather',
  [IconCategory.Other]: 'Other',
};